name: weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.4
  geolocator: ^8.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
